version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:840999370732:task-definition/flask-app:2"
        LoadBalancerInfo:
          ContainerName: "flask-app"
          ContainerPort: 5050
